import { useState, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  Box,
  Grid,
  Image,
  Text,
  NumberFormatter,
  Button,
  Flex,
} from "@mantine/core";
import { useCart } from "../../store/store";
import { Rating } from "@mantine/core";
import Link from "next/link";

const ProductPage = () => {
  const addProduct = useCart((state) => state.addProduct);
  const cart = useCart((state) => state.cart);
  const [quantity, setQuantity] = useState(0);
  const [product, setProduct] = useState();
  const router = useRouter();
  const { product_id } = router.query;
  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await fetch(
          `http://localhost:3000/api/getProduct?product_id=${product_id}`,
        );
        const product = await response.json();
        setProduct(product);
      } catch (error) {
        console.error(error);
      }
    };
    fetchData();
  }, [router.query]);
  const decreaseQuantity = () => {
    if (quantity > 0) {
      setQuantity((prevQuantity) => prevQuantity - 1);
    }
  };

  const increaseQuantity = () => {
    setQuantity((prevQuantity) => prevQuantity + 1);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" src="Logo.jpg" />
      </Head>
      {!!product ? (
        <Grid>
          <Grid.Col span={1}></Grid.Col>
          <Grid.Col span={3}>
            <Image
              src={"/product-img/" + product.product_id + ".jpg"}
              height={260}
              fit="contain"
            />
          </Grid.Col>
          <Grid.Col span={4}>
            <h1>
              <Text fw={500}>
                {product.product_name} {" ("}
                {product.unit_quantity}
                {")"}
              </Text>
              <Rating value={3.5} fractions={2} readOnly />
            </h1>
            <Text>
              <p style={{ textDecoration: "underline" }}>Price</p>
              <h1>
                <NumberFormatter
                  prefix="$"
                  value={product.unit_price}
                  thousandSeparator
                />
              </h1>
            </Text>
            <Text size="lg" my="lg">
              Input item quantity
            </Text>
            <Flex align="center">
              <Button
                size="sm"
                onClick={decreaseQuantity}
                mr="lg"
                style={{
                  backgroundColor: quantity === 0 ? "#DCDFE1" : "#50BEFE",
                }}
              >
                -
              </Button>
              {quantity}
              <Button
                size="sm"
                onClick={increaseQuantity}
                ml="lg"
                style={{ backgroundColor: "#50BEFE" }}
              >
                +
              </Button>
            </Flex>

            <Text size="sm" c="dimmed">
              <p style={{ textDecoration: "underline" }}>Description</p>
              {product.description}
            </Text>
          </Grid.Col>
          <Grid.Col
            span={3}
            style={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <Box my="xl">
              <Text size="lg" my="lg">
                Total Price
              </Text>
              <h3>
                <NumberFormatter
                  prefix="$"
                  value={(quantity * product.unit_price).toFixed(2)}
                  thousandSeparator
                />
              </h3>
              <p></p>
              <Button
                bg="green"
                my="xl"
                size="lg"
                onClick={() => {
                  addProduct(product, quantity);
                }}
              >
                Add to cart
              </Button>
              <div>
                <Button bg="red.5" my="xl" size="lg">
                  <Link
                    href="/shoppingcart"
                    style={{ color: "white", textDecoration: "none" }}
                  >
                    Check Out
                  </Link>
                </Button>
              </div>
            </Box>
          </Grid.Col>
          <Grid.Col span={1}></Grid.Col>
        </Grid>
      ) : null}
    </>
  );
};
export default ProductPage;
