import { useState, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { Box, Grid, Image, Text, NumberFormatter, Button } from "@mantine/core";
import { useCart } from "../../store/store";

const ProductPage = () => {
  const addProduct = useCart((state) => state.addProduct);
  const cart = useCart((state) => state.cart);
  console.log(cart);
  const [product, setProduct] = useState();
  const router = useRouter();
  const { product_id } = router.query;
  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await fetch(
          `http://localhost:3000/api/getProduct?product_id=${product_id}`,
        );
        const product = await response.json();
        setProduct(product);
      } catch (error) {
        console.error(error);
      }
    };
    fetchData();
  }, [router.query]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!!product ? (
        <Grid>
          <Grid.Col span={1}></Grid.Col>
          <Grid.Col span={3}>
            <Image
              src={"/product-img/" + product.product_id + ".jpg"}
              height={260}
              fit="contain"
            />
          </Grid.Col>
          <Grid.Col span={4}>
            <Text fw={500}>{product.product_name}</Text>
            <Text>
              <NumberFormatter
                prefix="$"
                value={product.unit_price}
                thousandSeparator
              />
              {" / "}
              {product.unit_quantity}
            </Text>
            <Text size="sm" c="dimmed">
              {product.description}
            </Text>
          </Grid.Col>
          <Grid.Col span={3}>
            <Text size="sm" c="dimmed">
              Total Price here
            </Text>
            <Button
              bg="green"
              my="xl"
              onClick={() => {
                addProduct(product);
              }}
            >
              Add to cart
            </Button>
            <div>
              <Button bg="red.5" my="xl" href="/shoppingcart">
                Check Out
              </Button>
            </div>
          </Grid.Col>
          <Grid.Col span={1}></Grid.Col>
        </Grid>
      ) : null}
    </>
  );
};
export default ProductPage;
