import ProductCard from "@/components/common/ProductCard";
import { Box, Center, Container, Grid } from "@mantine/core";
import { isArray, isEmpty } from "lodash";
import Head from "next/head";

export const getServerSideProps = async () => {
  const res = await fetch("http://localhost:3000/api/getAllProducts");
  const products = await res.json();

  return { props: { products } };
};

export default function Home(props) {
  const { products } = props;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        {isArray(products) && !isEmpty(products) ? (
          <Grid>
            {products.map((product) => (
              <Grid.Col key={product.product_id} span={4}>
                <ProductCard product={product} />
              </Grid.Col>
            ))}
          </Grid>
        ) : (
          <Center bg="var(--mantine-color-gray-light)">
            <Box>Network error</Box>
          </Center>
        )}
      </Container>
    </>
  );
}
