import Head from "next/head";
import Image from "next/image";
import { useEffect, useMemo, useState } from "react";

export const getServerSideProps = async () => {
  const res = await fetch("http://localhost:3000/api/getAllProducts");
  const products = await res.json();

  return { props: { products } };
};

export default function Home(props) {
  const { products } = props;

  console.log(products);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}
