import CartConfirm from "@/components/cart/CartConfirm";
import CartList from "@/components/cart/CartList";
import { useCart } from "@/store/store";
import { Box, Button, Container, Grid, Modal } from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import Head from "next/head";

const ShoppingCart = () => {
  const { cart, addProduct, subtractProduct, removeProduct, emptyCart } =
    useCart((state) => state);

  const [isOpened, { open, close }] = useDisclosure(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" src="Logo.jpg" />
      </Head>
      <Container fluid>
        <Grid>
          <Grid.Col span={2} />
          <Grid.Col span={8}>
            <Box>
              <Grid>
                <Grid.Col span={8}>
                  <CartList
                    cart={cart}
                    addProduct={addProduct}
                    subtractProduct={subtractProduct}
                    removeProduct={removeProduct}
                  />
                </Grid.Col>
                <Grid.Col span={4}>
                  <CartConfirm cart={cart} openConfirmation={open} />
                </Grid.Col>
              </Grid>
            </Box>
          </Grid.Col>
          <Grid.Col span={2} />
        </Grid>
      </Container>

      <Modal opened={isOpened} onClose={close} title="Delivery Information">
        <Box>
          <Button>Place an Order</Button>
        </Box>
      </Modal>
    </>
  );
};

export default ShoppingCart;
